// Pathful feature categories with their theme colors
export const FEATURE_CATEGORIES = {
  opportunities: {
    label: "Opportunity Universe",
    color: "gold",
    hsl: "40 85% 52%",
    icon: "Telescope",
    description: "Discover internships, scholarships, research positions, fellowships, and competitions curated for your path.",
  },
  roadmap: {
    label: "Career Roadmap",
    color: "green",
    hsl: "155 60% 40%",
    icon: "Compass",
    description: "Your personalized year-by-year career GPS, from freshman to graduation and beyond.",
  },
  readiness: {
    label: "Readiness Score",
    color: "blue",
    hsl: "220 70% 50%",
    icon: "Target",
    description: "Know exactly how prepared you are for any opportunity with our AI-powered readiness assessment.",
  },
  community: {
    label: "Community",
    color: "rose",
    hsl: "340 65% 55%",
    icon: "Users",
    description: "Connect with students who got in, mentors who can guide you, and peers on the same journey.",
  },
  feed: {
    label: "Daily Feed",
    color: "accent",
    hsl: "24 90% 55%",
    icon: "Rss",
    description: "Your personalized daily digest of opportunities, deadlines, tips, and community highlights.",
  },
  profiles: {
    label: "Opportunity Profiles",
    color: "teal",
    hsl: "175 60% 42%",
    icon: "FileText",
    description: "Deep-dive into every opportunity with resource bundles, alumni stories, and application tips.",
  },
} as const;

// Opportunity categories
export const OPPORTUNITY_CATEGORIES = [
  { value: "all", label: "All Opportunities" },
  { value: "internship", label: "Internships" },
  { value: "scholarship", label: "Scholarships" },
  { value: "research", label: "Research" },
  { value: "fellowship", label: "Fellowships" },
  { value: "competition", label: "Competitions" },
] as const;

// Mock opportunity data for the demo
export const MOCK_OPPORTUNITIES = [
  {
    id: 1,
    title: "Software Engineering Intern",
    organization: "Google",
    category: "internship",
    description: "Join Google's engineering team for a 12-week summer internship working on large-scale distributed systems.",
    location: "Mountain View, CA",
    locationType: "hybrid",
    deadline: "2026-05-15",
    salary: "$9,500/mo",
    tags: JSON.stringify(["Computer Science", "Software Engineering", "Paid"]),
    logoUrl: null,
    applicantCount: 45,
    matchScore: 92,
    isFeatured: true,
  },
  {
    id: 2,
    title: "Goldman Sachs Summer Analyst",
    organization: "Goldman Sachs",
    category: "internship",
    description: "10-week immersive program in investment banking, offering hands-on deal experience and mentorship.",
    location: "New York, NY",
    locationType: "onsite",
    deadline: "2026-04-30",
    salary: "$85K/yr prorated",
    tags: JSON.stringify(["Finance", "Business", "Paid"]),
    logoUrl: null,
    applicantCount: 120,
    matchScore: 78,
    isFeatured: true,
  },
  {
    id: 3,
    title: "Gates Millennium Scholarship",
    organization: "Bill & Melinda Gates Foundation",
    category: "scholarship",
    description: "Full ride scholarship for outstanding minority students with significant financial need and leadership potential.",
    location: "Nationwide",
    locationType: "remote",
    deadline: "2026-06-01",
    salary: "Full tuition",
    tags: JSON.stringify(["Any Major", "Undergrad", "Full Ride"]),
    logoUrl: null,
    applicantCount: 200,
    matchScore: 85,
    isFeatured: false,
  },
  {
    id: 4,
    title: "NASA Pathways Intern",
    organization: "NASA",
    category: "internship",
    description: "Work alongside NASA engineers and scientists on cutting-edge space exploration projects.",
    location: "Houston, TX",
    locationType: "onsite",
    deadline: "2026-05-20",
    salary: "$7,200/mo",
    tags: JSON.stringify(["Engineering", "STEM", "Government"]),
    logoUrl: null,
    applicantCount: 32,
    matchScore: 88,
    isFeatured: false,
  },
  {
    id: 5,
    title: "Undergraduate Research Fellow",
    organization: "MIT Media Lab",
    category: "research",
    description: "Join a research group at the MIT Media Lab exploring AI, human-computer interaction, and creative technologies.",
    location: "Cambridge, MA",
    locationType: "onsite",
    deadline: "2026-06-15",
    salary: "$6,000 stipend",
    tags: JSON.stringify(["Research", "AI", "HCI"]),
    logoUrl: null,
    applicantCount: 18,
    matchScore: 95,
    isFeatured: true,
  },
  {
    id: 6,
    title: "Rhodes Scholarship",
    organization: "Rhodes Trust",
    category: "fellowship",
    description: "The world's oldest and most prestigious international scholarship for postgraduate study at Oxford.",
    location: "Oxford, UK",
    locationType: "onsite",
    deadline: "2026-10-01",
    salary: "Full funding",
    tags: JSON.stringify(["Any Major", "Graduate", "International"]),
    logoUrl: null,
    applicantCount: 55,
    matchScore: 72,
    isFeatured: false,
  },
  {
    id: 7,
    title: "HackMIT 2026",
    organization: "MIT",
    category: "competition",
    description: "Annual 24-hour hackathon bringing together 1,000+ hackers to build innovative projects.",
    location: "Cambridge, MA",
    locationType: "onsite",
    deadline: "2026-08-01",
    salary: "$10K grand prize",
    tags: JSON.stringify(["Hackathon", "Tech", "Team"]),
    logoUrl: null,
    applicantCount: 8,
    matchScore: 90,
    isFeatured: false,
  },
  {
    id: 8,
    title: "Apple Machine Learning Intern",
    organization: "Apple",
    category: "internship",
    description: "Work on next-generation ML models powering Apple Intelligence across all Apple devices.",
    location: "Cupertino, CA",
    locationType: "onsite",
    deadline: "2026-05-01",
    salary: "$10,200/mo",
    tags: JSON.stringify(["Machine Learning", "AI", "Paid"]),
    logoUrl: null,
    applicantCount: 67,
    matchScore: 82,
    isFeatured: true,
  },
];

// Mock stories
export const MOCK_STORIES = [
  {
    id: 1,
    authorName: "Maya Johnson",
    authorAvatar: null,
    university: "Stanford University",
    title: "How I Landed My Dream Internship at Google",
    content: "I never thought I'd make it. Coming from a small town, I didn't have the network or the fancy resume. But Pathful showed me exactly what I needed to do — step by step. The readiness score helped me identify gaps in my profile, and the community connected me with a Google engineer who became my mentor.",
    opportunityTitle: "Software Engineering Intern at Google",
    category: "got-in",
    likes: 234,
  },
  {
    id: 2,
    authorName: "Carlos Rivera",
    authorAvatar: null,
    university: "UT Austin",
    title: "From Community College to NASA",
    content: "My journey wasn't traditional. I started at a community college, transferred to UT Austin, and through Pathful's roadmap engine, I mapped out every milestone I needed to hit. The opportunity profile for NASA showed me exactly what they look for. I applied, and I got in.",
    opportunityTitle: "NASA Pathways Intern",
    category: "got-in",
    likes: 187,
  },
  {
    id: 3,
    authorName: "Aisha Williams",
    authorAvatar: null,
    university: "Howard University",
    title: "The Scholarship That Changed Everything",
    content: "As a first-gen student, I didn't even know the Gates Scholarship existed until Pathful's daily feed showed it to me. The readiness score said I was 89% ready, and the resource bundle gave me everything I needed for my application.",
    opportunityTitle: "Gates Millennium Scholarship",
    category: "got-in",
    likes: 312,
  },
  {
    id: 4,
    authorName: "James Chen",
    authorAvatar: null,
    university: "UC Berkeley",
    title: "Tips for Your First Research Position",
    content: "Here's what I wish someone told me: reach out to professors directly, attend their office hours, and read at least two of their recent papers before your meeting. Pathful's opportunity profiles had all this info in one place.",
    opportunityTitle: null,
    category: "advice",
    likes: 156,
  },
];

// Roadmap milestones
export const MOCK_MILESTONES = {
  freshman: [
    { title: "Declare your major (or explore)", category: "academic", isCompleted: true },
    { title: "Join 2-3 student organizations", category: "extracurricular", isCompleted: true },
    { title: "Attend your first career fair", category: "professional", isCompleted: true },
    { title: "Build your LinkedIn profile", category: "professional", isCompleted: false },
    { title: "Start a personal project or portfolio", category: "professional", isCompleted: false },
  ],
  sophomore: [
    { title: "Land your first internship or research role", category: "professional", isCompleted: false },
    { title: "Take leadership in a student org", category: "extracurricular", isCompleted: false },
    { title: "Build relationships with 2-3 professors", category: "academic", isCompleted: false },
    { title: "Complete relevant online certifications", category: "academic", isCompleted: false },
    { title: "Attend industry conferences or meetups", category: "professional", isCompleted: false },
  ],
  junior: [
    { title: "Secure a competitive summer internship", category: "professional", isCompleted: false },
    { title: "Apply for scholarships and fellowships", category: "academic", isCompleted: false },
    { title: "Start preparing for graduate school (if applicable)", category: "academic", isCompleted: false },
    { title: "Contribute to open source or publish research", category: "professional", isCompleted: false },
    { title: "Mentor underclassmen in your field", category: "extracurricular", isCompleted: false },
  ],
  senior: [
    { title: "Apply for full-time positions or grad programs", category: "professional", isCompleted: false },
    { title: "Complete your capstone or thesis", category: "academic", isCompleted: false },
    { title: "Negotiate your first offer", category: "professional", isCompleted: false },
    { title: "Pay it forward — become a Pathful mentor", category: "extracurricular", isCompleted: false },
  ],
};

// Readiness quiz questions
export const READINESS_QUESTIONS = [
  {
    id: 1,
    question: "What year are you in college?",
    options: ["Freshman", "Sophomore", "Junior", "Senior", "Graduate"],
  },
  {
    id: 2,
    question: "What's your primary field of study?",
    options: ["STEM", "Business", "Humanities", "Social Sciences", "Arts", "Undecided"],
  },
  {
    id: 3,
    question: "How many internships or work experiences have you had?",
    options: ["None yet", "1", "2-3", "4+"],
  },
  {
    id: 4,
    question: "Do you have a polished resume and LinkedIn profile?",
    options: ["Not yet", "Resume only", "Both but need improvement", "Yes, both are strong"],
  },
  {
    id: 5,
    question: "Have you participated in any extracurricular activities or leadership roles?",
    options: ["None", "Member of clubs", "Leadership in 1-2 orgs", "Significant leadership experience"],
  },
  {
    id: 6,
    question: "What type of opportunities are you most interested in?",
    options: ["Internships", "Scholarships", "Research", "Fellowships", "Competitions", "All of the above"],
  },
];

// Navigation items for the dashboard sidebar
export const NAV_ITEMS = {
  discover: [
    { title: "Opportunity Feed", href: "/dashboard", icon: "Compass" },
    { title: "Scholarships", href: "/dashboard/scholarships", icon: "GraduationCap" },
    { title: "Research", href: "/dashboard/research", icon: "Microscope" },
    { title: "Competitions", href: "/dashboard/competitions", icon: "Trophy" },
  ],
  myPath: [
    { title: "Career Roadmap", href: "/roadmap", icon: "Map" },
    { title: "Readiness Score", href: "/readiness", icon: "Target" },
    { title: "Saved", href: "/saved", icon: "Bookmark" },
    { title: "Applications", href: "/applications", icon: "Send" },
  ],
  connect: [
    { title: "Community", href: "/community", icon: "Users" },
    { title: "Mentors", href: "/mentors", icon: "Heart" },
    { title: "My Stories", href: "/stories", icon: "PenSquare" },
  ],
};
